### ISSUE TITLE
Colors are a bit garish

### ISSUE THREAD

**Issue by jldugger** [TrippW/onitama#2]
Colors right now are fully saturated, `#ff0000`  and `#0000ff`. This makes it particularly hard to read black text on blue backgrounds. I recommend desaturating them a bit. I was intending to make a patch, but it seems like maybe Color is a bit more prolific than expected in the code base such that a two liner patch is not sufficient.

**Comment by jldugger** [comment]
Might I suggest `#f5544e` and `#4e96f5` instead?

**Comment by TrippW** [comment]
Absolutely. I've updated to use the suggested colors.
